### ISSUE TITLE
Add option to suppress console output or add some simple stats

### ISSUE THREAD

**Issue by wingedfox** [campbes/grunt-complexity-report#1]
Hi,
Thanks for improvements to grunt-complexity!

It would be nice to have a feature to suppress console output to not pollute CI environment.
May you add this and/or create console reporter like 'dots' for Karma?

**Comment by campbes** [comment]
You're right, the console output is pretty OTT. The original grunt-complexity had a much nicer console output - I just wanted everything to start consistent. At the very least, it could be slimmed down or summarised.

Feel free to raise a pull request - or it will probably take me a while to get around to it myself....

**Comment by campbes** [comment]
Closing as functionality added in 0.0.5
